name: "Get Vega Version"
description: "Greet someone and record the time"
inputs:
  include-preview-versions:
    description: "If you want preview versions of the app. Not compatible with latest."
    required: false
  latest:
    description: "Get the version marked as latest. Not compatible with include-preview-versions."
    required: false
  previous-version:
    description: "Check the found version against an existing version, to see if there is a new version"
    default: "v0.0.0"
    required: false
outputs:
  current-version:
    description: "The current Vega version"
  new-version:
    description: "If there is a new version compared to the previous version inputted. False if no previous version is given."
runs:
  using: "node20"
  main: "index.js"
